# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-01-16 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(default='3', max_length=10),
        ),
    ]
