version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: python_tests
          command: |
              docker-compose -f /home/circleci/project/compose/docker-compose.yml run uwsgi bash -c "sleep 15 && python manage.py makemigrations && python manage.py test"
