version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
        name: makemigrations
        command: docker-compose -f /home/ubuntu/cogat/compose/docker-compose-circle.yml run uwsgi python manage.py makemigrations
      - run:
        name: python_tests
        command: docker-compose -f /home/ubuntu/cogat/compose/docker-compose-circle.yml run uwsgi python manage.py test
