version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: python_tests
          command: |
            docker-compose -f /home/ubuntu/cogat/compose/docker-compose-circle.yml run uwsgi python manage.py makemigrations
            docker-compose -f /home/ubuntu/cogat/compose/docker-compose-circle.yml run uwsgi python manage.py test
