graphdb:
  build: .
  dockerfile: ./graphdb/Dockerfile
  hostname: graphdb
  volumes:
    - ./graphdb/data:/opt/data
    - ./graphdb/neo4j/conf/neo4j-server.properties:/var/lib/neo4j/conf/neo4j-server.properties 
    - ./graphdb/neo4j/conf/neo4j.properties:/var/lib/neo4j/conf/neo4j.properties 
  ports:
    - "7474:7474"
    - "1337:1337"
    - "5001:5001"
    - "6002:6002"

postgres:
    image: postgres:9.4
    env_file: .env
    expose:
        - "5432"

uwsgi:
    build: .
    dockerfile: ./uwsgi/Dockerfile
    command: /code/compose/uwsgi/uwsgi.sh
    restart: always
    env_file: .env
    volumes:
        - ..:/code
        - /var/www/static
    links:
        - postgres
        - graphdb

nginx:
    restart: always
    image: nginx
    volumes_from:
        - uwsgi
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/uwsgi_params.par:/etc/nginx/uwsgi_params.par:ro
    links:
        - uwsgi
    ports:
        - "80:80"
